submodule:
  wTools:
    path: 'npm:///wTools'
    enabled: 0
  wCopyable:
    path: 'npm:///wCopyable'
    enabled: 0
  wPathBasic:
    path: 'npm:///wpathbasic'
    enabled: 0
  wVerbal:
    path: 'npm:///wverbal'
    enabled: 0
  wFiles:
    path: 'npm:///wFiles'
    enabled: 0
  wStarter:
    path: 'npm:///wstarter'
    enabled: 0
  wCommandsAggregator:
    path: 'npm:///wcommandsaggregator'
    enabled: 0
  wCommandsConfig:
    path: 'npm:///wcommandsconfig'
    enabled: 0
  wStateStorage:
    path: 'npm:///wstatestorage'
    enabled: 0
  wStateSession:
    path: 'npm:///wstatesession'
    enabled: 0
  google-closure-compiler-js:
    path: 'npm:///google-closure-compiler-js#20200517.0.0'
    enabled: 0
  uglify-es:
    path: 'npm:///uglify-es#3.3.9'
    enabled: 0
  babylon:
    path: 'npm:///babylon#6.18.0'
    enabled: 0
  babel-core:
    path: 'npm:///@babel/core#7.11.6'
    enabled: 0
  babel-polyfill:
    path: 'npm:///@babel/polyfill#7.11.5'
    enabled: 0
  babel-preset-stage-0:
    path: 'npm:///@babel/preset-stage-0#7.8.3'
    enabled: 0
  babel-preset-stage-1:
    path: 'npm:///@babel/preset-stage-1#7.8.3'
    enabled: 0
  babel-preset-stage-2:
    path: 'npm:///@babel/preset-stage-2#7.8.3'
    enabled: 0
  babel-preset-stage-3:
    path: 'npm:///@babel/preset-stage-3#7.8.3'
    enabled: 0
  babel-preset-env:
    path: 'npm:///@babel/preset-env#7.11.5'
    enabled: 0
  babel-preset-es2015:
    path: 'npm:///babel-preset-es2015#6.24.1'
    enabled: 0
  babel-preset-es2015-without-strict:
    path: 'npm:///babel-preset-es2015-without-strict#0.0.4'
    enabled: 0
  babel-preset-node6-without-strict:
    path: 'npm:///babel-preset-node6-without-strict#0.0.1'
    enabled: 0
  babel-plugin-transform-runtime:
    path: 'npm:///@babel/plugin-transform-runtime#7.11.5'
    enabled: 0
  babel-plugin-transform-class-properties:
    path: 'npm:///@babel/plugin-proposal-class-properties#7.10.4'
    enabled: 0
  wtranspile:
    path: 'hd://.'
    enabled: 0
    criterion:
      development: 1
  wTesting:
    path: 'npm:///wTesting'
    enabled: 0
    criterion:
      development: 1
  eslint:
    path: 'npm:///eslint#7.1.0'
    enabled: 0
    criterion:
      development: 1
path:
  in: .
  out: out
  temp:
    - 'path::out'
    - package-lock.json
    - package.json
    - node_modules
  proto: ./proto
  export: '{path::proto}/**'
  doc: ./doc
  out.raw.debug:
    path: '{path::out}/debug'
    criterion:
      debug: debug
      raw: raw
      content: prime
  out.compiled.debug:
    path: '{path::out}/compiled.debug'
    criterion:
      debug: debug
      raw: compiled
      content: prime
  out.raw.release:
    path: '{path::out}/raw.release'
    criterion:
      debug: release
      raw: raw
      content: prime
  out.compiled.release:
    path: '{path::out}/release'
    criterion:
      debug: release
      raw: compiled
      content: prime
  entry.proto.no.tests:
    path: proto/wtools/atop/transpile/MainBase.s
    criterion:
      tests: no.tests
  entry.proto.only.tests:
    path: proto/**/*.test.s
    criterion:
      tests: only.tests
  entry.out.raw.debug:
    path: '{path::out.*=1}/source/wtools/atop/transpile/MainBase.s'
    criterion:
      debug:
        - debug
        - release
      raw: raw
      content: prime
  entry.out.compiled.debug:
    path: '{path::out.*=}/source/Index.s'
    criterion:
      debug:
        - debug
        - release
      raw: compiled
      content: prime
  npm.proto.entry:
    - /pro/module/wTranspile/proto/wtools/atop/transpile/entry/Include.s
    - /pro/module/wTranspile/proto/node_modules/wtranspile
reflector:
  reflect.proto:
    inherit: predefined.*
    criterion:
      tests: no.tests
      debug:
        - debug
        - release
      raw:
        - raw
        - compiled
      content: prime
    filePath:
      'path::proto': '{path::out.*=1}/source'
  transpile.proto.raw:
    inherit: predefined.*
    step:
      inherit: files.transpile
      entry: 'path::entry.proto.no.tests'
    criterion:
      raw: raw
      debug: release
      content: prime
    filePath:
      'path::proto': '{path::out.raw.release}'
  transpile.proto.no.tests.compiled:
    inherit: predefined.*
    step:
      inherit: files.transpile
      entry: 'path::entry.proto.*=1'
    criterion:
      tests: no.tests
      raw: compiled
      debug:
        - debug
        - release
      content: prime
    filePath:
      '**.test*': 0
      '**.test/**': 0
      'path::proto': '{path::out.*=1}/Main.s'
  transpile.proto.only.tests.compiled:
    inherit: predefined.*
    step:
      inherit: files.transpile
      entry: 'path::entry.proto.*=1'
      external.before: '{path::out.*=1}/Main.s'
    criterion:
      tests: only.tests
      raw: compiled
      debug:
        - debug
        - release
      content: prime
    filePath:
      '**.test*': 1
      'path::proto': '{path::out.*=1}/Tests.test.s'
step:
  npm.generate:
    inherit: npm.generate
    entryPath: 'path::entry.out.*=1'
    packagePath: '{path::out.*=1}/package.json'
    filesPath: '{path::out.*=1}/source/**'
    criterion:
      debug:
        - debug
        - release
      raw:
        - raw
        - compiled
  clean.out:
    inherit: files.delete
    filePath: '{path::out.*=1}/source'
    criterion:
      debug:
        - debug
        - release
      raw:
        - raw
        - compiled
      tests:
        - no.tests
        - only.tests
      content:
        - prime
        - npm
  clean.out.npm:
    inherit: files.delete
    filePath: 'path::out.*=1'
    criterion:
      debug: debug
      raw: compiled
      tests: no.tests
      content: npm
  tst.proto:
    shell: 'tst {path::proto}'
    criterion:
      content: proto
  tst.debug:
    shell: 'tst {path::out.*=1}'
    criterion:
      content: prime
      debug: debug
  tst.release:
    shell: 'tst {path::out.*=1}'
    criterion:
      content: prime
      debug: release
build:
  debug:
    criterion:
      default: 1
      debug: debug
      raw: raw
      content: prime
    steps:
      - 'step::clean.out*=2'
      - reflect.proto.*=1
  compiled.debug:
    criterion:
      debug: debug
      raw: compiled
      content: prime
    steps:
      - 'step::clean.out*=2'
      - transpile.proto.no.tests*=1
      - transpile.proto.only.tests*=1
  raw.release:
    criterion:
      debug: release
      raw: raw
      content: prime
    steps:
      - 'step::clean.out*=2'
      - transpile.proto.raw
  release:
    criterion:
      debug: release
      raw: compiled
      content: prime
    steps:
      - 'step::clean.out*=2'
      - transpile.proto.no.tests*=1
      - transpile.proto.only.tests*=1
  npm:
    criterion:
      debug: debug
      raw: raw
      content: npm
    steps:
      - npm.generate.*=1
  all:
    steps:
      - 'build::debug'
      - 'build::compiled.debug'
      - 'build::raw.release'
      - 'build::release'
      - 'build::npm'
